# Generated by Django 4.1.7 on 2023-03-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tv',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
