# Generated by Django 4.1.7 on 2023-03-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_movie_image_tv_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='heading',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tv',
            name='heading',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tv',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
