# Generated by Django 4.1.7 on 2023-04-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_genre_movie_genre_tv_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='blog.genre'),
        ),
        migrations.AddField(
            model_name='tv',
            name='genre',
            field=models.ManyToManyField(to='blog.genre'),
        ),
    ]
