# Generated by Django 4.1.7 on 2023-04-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_movie_genre_remove_tv_genre_movie_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tv',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
