# Generated by Django 4.1.7 on 2023-07-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_movie_cast_alter_movie_synopsis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
