# Generated by Django 4.1.7 on 2023-07-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='cast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='image',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='synopsis',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
