# Generated by Django 4.1.7 on 2023-07-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_tv_cast_alter_tv_image_alter_tv_synopsis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
